# This workflow is triggered on push or pull request for the master branch.
# It verifies that the code is safe to merge.
---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GO_VERSION: "1.14"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check goimports
        run: |
          go install golang.org/x/tools/cmd/goimports
          if [[ $(goimports -l cmd internal pkg) ]]; then
            echo 'Please run `goimports -w cmd internal pkg`.'
            false
          fi

      - name: Check go mod
        run: |
          go mod tidy
          if ! git diff --quiet; then
            echo 'Please run `go mod tidy`.'
            false
          fi

      - name: Check for license headers
        run: |
          go get -u github.com/google/addlicense
          addlicense -check cmd internal pkg

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Check YAML
        run: |
          yamllint .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run tests
        run: |
          go test -v ./...
